[package]
name = "rchat"
version = "0.1.0"
edition = "2021"
author = "Chris Conlon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
async-std = "1"
clap = { version = "4.1.9", features = ["derive"] }
